@startuml
left to right direction

actor "Customer" as Customer
actor "Admin" as Admin
actor "Staff" as Staff

rectangle "Reservation System" {
    usecase "Login" as UC1
    usecase "View Tables" as UC2
    usecase "Make Reservation" as UC3
    usecase "Modify Reservation" as UC4
    usecase "Cancel Reservation" as UC5
    usecase "Manage Reservations" as UC6
    usecase "Update Table Availability" as UC7
}

Customer --> UC1
Customer --> UC2
Customer --> UC3
Customer --> UC4
Customer --> UC5
Staff --> UC6
Staff --> UC7
Admin --> UC6
@enduml
